const dotenv = require('dotenv');
dotenv.config();

const {
    ACCESS_TOKEN_SECRET_KEY,
    ACCESS_TOKEN_LIFE,
    REFRESH_TOKEN_SECRET_KEY,
    REFRESH_TOKEN_LIFE,
    SALT_ROUNDS,
    ROLE_LEARNER,
    ROLE_MEMBER,
    ROLE_ADMIN,
} = process.env;

module.exports = {
    ACCESS_TOKEN_SECRET_KEY: ACCESS_TOKEN_LIFE,
    ACCESS_TOKEN_LIFE: ACCESS_TOKEN_LIFE,
    REFRESH_TOKEN_SECRET_KEY: REFRESH_TOKEN_SECRET_KEY,
    REFRESH_TOKEN_LIFE: REFRESH_TOKEN_LIFE,
    SALT_ROUNDS: parseInt(SALT_ROUNDS),
    ROLE_LEARNER: ROLE_LEARNER,
    ROLE_MEMBER: ROLE_MEMBER,
    ROLE_ADMIN: ROLE_ADMIN,
};
